---

argocd_namespace: openshift-gitops
argocd_operator_starting_cluster_service_version: v0.13.0
openshift_gitops_operator_starting_cluster_service_version: v1.17.1
argocd_operator_channel: gitops-1.17
argocd_enable_label_management: "true"
argocd_value_file: values-okd.yaml
