---
okd_configuration_validity_duration_s: 21600  # 6 hours
okd_samples_operator_removed: false

create_local_files_network_type: OpenShiftSDN
create_local_files_machine_networks:
  - cidr: 192.168.60.0/24
create_local_files_platform: "none"

opt_out_of_remote_health_reporting: false

set_etc_hostname_in_ignition_file: false

use_cluster_proxy: false
use_disconnected_registry: false
use_custom_container_registry: false
